spring:
  application:
    name: ms-account
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/project}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  logging:
    level:
      org.hibernate.SQL: debug
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      enabled: true
    enabled: true
  sql:
    init:
      platform: postgres
server:
  port: 9092

random: 999999999